### ISSUE TITLE
Unable to request widevine license (400):

### ISSUE THREAD

**Issue by Mancy** [DevLARLEY/LearnystDownloader#5]
what could be the reason for the drm-u POST request to return this error

Unable to request widevine license (400):
 {"errorcode":9,"txnId":555555555555}

**Comment by DevLARLEY** [comment]
It doesn't seem like they broke anything. Can you post your URL and lrToken? (Or send them to me via discord @larley)

**Comment by tushar89887** [comment]
> what could be the reason for the drm-u POST request to return this error
> 
> Unable to request widevine license (400): {"errorcode":9,"txnId":555555555555}

same problem unable to request 1st licence (400), error code 31 txnID: 555555555, DEVLarley, any solution so far?
